services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "alembic upgrade head && 
             uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    env_file:
      - .env
    ports:
      - 8000:80
    restart: always
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - "5432:5432"
    restart: always
