"""Create fav cafe and added phone number to cafe

Revision ID: 208857336d1e
Revises: d119af189950
Create Date: 2023-06-21 19:09:36.108974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208857336d1e'
down_revision = 'd119af189950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cafe', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafe', 'phone_number')
    op.drop_table('favourite_cafe')
    # ### end Alembic commands ###
