"""Created cafe, image, city models

Revision ID: 43ffd7f6b921
Revises: 
Create Date: 2023-06-07 18:21:24.076955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ffd7f6b921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('places', sa.Integer(), nullable=True),
    sa.Column('average_bill', sa.Enum('CHEAP', 'MIDDLE', 'EXPENSIVE', name='averagebill'), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('work_time_start', sa.Time(), nullable=True),
    sa.Column('work_time_end', sa.Time(), nullable=True),
    sa.Column('has_wifi', sa.BOOLEAN(), nullable=True),
    sa.Column('has_coworking_place', sa.BOOLEAN(), nullable=True),
    sa.Column('can_with_pets', sa.BOOLEAN(), nullable=True),
    sa.Column('has_outdoor_seating', sa.BOOLEAN(), nullable=True),
    sa.Column('has_vegan_menu', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('cafe')
    op.drop_table('city')
    # ### end Alembic commands ###
