"""Added phone number field to cafe model

Revision ID: aa7e2b4f66da
Revises: ddef4fdff812
Create Date: 2023-06-20 12:29:31.192829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7e2b4f66da'
down_revision = 'ddef4fdff812'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafe', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafe', 'phone_number')
    # ### end Alembic commands ###
