"""Added new model favourite cafe

Revision ID: dc5be5ab754b
Revises: aa7e2b4f66da
Create Date: 2023-06-20 13:19:56.654631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5be5ab754b'
down_revision = 'aa7e2b4f66da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
